### PR TITLE
 Pass already existing xml chunk into getFullContext method

### PR DESCRIPTION
**Pull request by ThatcherK**

### CODE REVIEW

**Comment by akmiller01** [comment]
This is working well, @ThatcherK . I know it wasn't in the original ticket, but could you also implement it for 4.3.1 error for title elements too? I think it would be very useful in the same way, as title can occur at multiple locations:

image

**Comment by akmiller01** [comment]
Also @ThatcherK are you getting Redis errors while the function is running? For some reason on the develop branch I do not get these, but when executing your branch I do:
```
[2023-06-21T12:56:08.168Z] Redis: Unable to connect to the redis database:  SocketClosedUnexpectedlyError: Socket closed unexpectedly
[2023-06-21T12:56:08.168Z]     at TLSSocket.<anonymous> (/home/alex/git/js-validator-api/node_modules/@redis/client/dist/lib/client/socket.js:185:118)
[2023-06-21T12:56:08.168Z]     at Object.onceWrapper (node:events:628:26)
[2023-06-21T12:56:08.168Z]     at TLSSocket.emit (node:events:525:35)
[2023-06-21T12:56:08.169Z]     at node:net:301:12
[2023-06-21T12:56:08.169Z]     at TCP.done (node:_tls_wrap:588:7)
[2023-06-21T12:56:08.169Z]     at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
[2023-06-21T12:56:08.561Z] {
[2023-06-21T12:56:08.561Z]   name: 'redisConnect',
[2023-06-21T12:56:08.561Z]   value: 'Redis: Connection to redis-iati-dev.redis.cache.windows.net ready'
[2023-06-21T12:56:08.561Z] }

```

**Comment by ThatcherK** [comment]
@akmiller01 I don't get the redis errors on my side

**Comment by ThatcherK** [comment]
@akmiller01 I've added more description to the title errors, please review!

**Review by akmiller01 — APPROVED** [review]
Looks good, and works fast!

**Pull request merged**
